blogdjango/blog/urls.py
from unicodedata import name
from django.urls import path
from . import views


urlpatterns = [
    path("", views.PostList.as_view(), name="home"),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('/about_blog/', views.AboutBlog.as_view(), name='about_blog'),
    path('add_post', views.AddPostView.as_view(), name='add_post'),
    path('/edit/<int:pk>', views.UpdatePostView.as_view(), name='update_post'),
]

blogdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogdjango.blog.urls')),
]

blogdjango/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
STATUS = (
    (0, "Draft"),
    (1, "Publish"),
)

class Post(models.Model):
    """
    Class Post for insert information about post in database.
    Args:
        models (_type_): _description_
        models a modeling de information for connect a database

    Returns:
        _type_: _description_
        Ordering: order based a last post
        

    """
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    updated_on = models.DateTimeField(auto_now = True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status_post = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.content = self.content.upper()
        super().save(*args, **kwargs)    

    def get_absolute_url(self):
        return reverse('home')

class AboutBlog(models.Model):
    content = models.TextField()


    def __str__(self):
        return self.content

        

blogdjango/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'slug', 'status_post', 'author', 'content')

        widget = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'status_post': forms.Select(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }    


class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'slug', 'status_post', 'author', 'content')

        widget = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'status_post': forms.Select(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }    

blogdjango/blog/views.py
from django.shortcuts import render
from blogdjango.blog.forms import EditForm, PostForm
from blogdjango.blog.models import Post, AboutBlog 
from django.views.generic import DetailView, ListView, CreateView, UpdateView

class PostList(ListView):
    queryset = Post.objects.filter(status_post=1).order_by('-created_on')
    template_name = 'index.html'

class PostDetail(DetailView):
    model = Post
    template_name = 'post_detail.html'


class AboutBlog(ListView):
    queryset = AboutBlog.objects.all()
    model = AboutBlog
    template_name = 'about_blog.html'
        

class AddPostView(CreateView):
    model = Post
    form_class = EditForm
    template_name = 'add_post.html' 
    

class UpdatePostView(UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'update_post.html'
   

templates/about_blog.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block content %}

<div class="col-md-8 mt-3 left">
    <div class="card mb-4">
        <div class="card-body">
            <p class="card-text ">
              Olá! primeiramente seja bem vindo ao blog django estamos felizes por está aqui. Bem, tudo começou quando conheci programação na faculdade, detalhe era bacharel de Produção.
              Primeiro contato foi com a linguagem pascal que tem como intuito a aprendizagem, e acabei reparando que tinha uma certa "facilidade" assim, por ser curioso busquei informações sobre o assunto. Logo me encantou a linguagem python.
              Desde então, sigo meu aprendizado em python e o framework django para busca a minha oportunidade no mercado de trabalho. 
            </p>
        </div>
    </div>



{% endblock content %}

templates/add_post.html
{% extends "base.html" %}

{% block content %}
<h4> Adcionar Postagem </h4>


<form method="POST">
  <div class="form-control">   
    {% csrf_token %}
    {{form.as_p}}
  </div>
  <button type="submit" class="btn btn-primary">Enviar</button>
</form>



{% endblock content %}



{% include footer %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

    <head>
        {% block title %}<title>Blog Django </title>{% endblock title %}
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }
        .masthead {
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">Blog Django </a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="{% url 'add_post' %}">Adcionar Post</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}

        <!-- Footer -->
        {% block footer %}
            <footer class="py-3 bg-grey">
                <p class="m-0 text-dark text-center ">Copyright &copy; Blog Django </p>      
            </footer>
        {% endblock footer %}
    </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Bem vindo ao Blog Django, este é um blog sobre assuntos de Python e Django! &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                        <a href="{% url 'update_post' post.pk %}">Editar Postagem</a>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'post_detail' post.slug %}" class="btn btn-primary">Leia mais &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
  </div>
</div>

{% endblock content %}

templates/sidebar.html
{% block sidebar %}



    <!-- Sidebar Widgets Column -->
    <div class="col-md-4 float-right ">
        <div class="card my-4">
            <h5 class="card-header">Sobre nós</h5>
            <div class="card-body">
                <p class="card-text">Bem-vindo ao Blog Django, sua fonte número um para todas as notícias e informações relacionadas ao django e python. Estamos dedicados a fornecer a você o melhor conteúdo, com ênfase nos padrões da comunidade.

                    Esperamos que você goste do conteúdo do Blog Django tanto quanto gostamos de editá-los para você.</p>
                <a href="{% url 'about_blog' %}" class="btn btn-danger">Saiba Mais</a>
            </div>
        </div>
    </div>

{% endblock sidebar %}
© 2022 GitHub, Inc.
Terms
Privacy
Security
Status
Docs

templates/update_post.html
{% extends "base.html" %}

{% block content %}
<h4>Editar Postagem do Blog</h4>
</br>

<form method="POST">
  <div class="form-control">   
    {% csrf_token %}
    {{form.as_p}}
  </div>
  <button type="submit" class="btn btn-primary">Atualizar</button>
</form>



{% endblock content %}



{% include footer %}